# Generated by Django 5.2 on 2025-04-18 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloPresetado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Modelo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo do Modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Mobilidade')),
                ('data_avaliacao', models.DateField(verbose_name='Data')),
                ('lado_esquerdo', models.CharField(max_length=100, verbose_name='Lado Esquerdo')),
                ('lado_direito', models.CharField(max_length=100, verbose_name='Lado Direito')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilidades', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-data_avaliacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(auto_now_add=True, verbose_name='Data da Avaliação')),
                ('conteudo', models.TextField(blank=True, null=True, verbose_name='Conteúdo')),
                ('modelo_presetado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.modelopresetado', verbose_name='Modelo Pré-Setado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_clinicos', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ForcaMuscular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musculatura', models.CharField(max_length=100, verbose_name='Musculatura')),
                ('data_avaliacao', models.DateField(verbose_name='Data')),
                ('lado_esquerdo', models.CharField(max_length=100, verbose_name='Lado Esquerdo')),
                ('lado_direito', models.CharField(max_length=100, verbose_name='Lado Direito')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dadosdeforcamuscular', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='EscalaseQuestionários',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_avaliacao', models.DateField(verbose_name='Data')),
                ('resultado', models.CharField(max_length=100, verbose_name='Resultado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalasequestionarios', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='TodosTestes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.categoriateste')),
            ],
        ),
        migrations.CreateModel(
            name='TesteFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(verbose_name='Data')),
                ('lado_esquerdo', models.CharField(max_length=100, verbose_name='Lado Esquerdo')),
                ('lado_direito', models.CharField(max_length=100, verbose_name='Lado Direito')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dadosdetestes', to='pacientes.paciente')),
                ('teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.todostestes')),
            ],
        ),
    ]
