# Generated by Django 5.2 on 2025-05-05 16:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoclinico',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date.today, verbose_name='Data da Avaliação'),
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora do Agendamento')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo da Consulta')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20, verbose_name='Status do Agendamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
