# Generated by Django 5.2 on 2025-05-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_historicoclinico_data_avaliacao_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo da Consulta'),
        ),
    ]
