# Generated by Django 5.2 on 2025-05-28 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_registrosessao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosessao',
            name='regioes_de_dor',
        ),
        migrations.CreateModel(
            name='RegiaoDor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(max_length=50)),
                ('valor', models.PositiveSmallIntegerField()),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regioes', to='pacientes.registrosessao')),
            ],
        ),
    ]
